[package]
name = "codedigger"
version = "0.1.0"
authors = ["lsongzhi <lsongzhi@163.com>"]
edition = "2018"
[dependencies]
threadpool = "1.7.1"
serde_json = "1.0.32"
indicatif = "0.11.0"
serde = "1.0.83"
serde_derive="1.0.83"
toml = "0.4"
num_cpus = "1.9.0"